/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    '/health': {
        parameters: {
            query?: never
            header?: never
            path?: never
            cookie?: never
        }
        get: operations['getHealth']
        put?: never
        post?: never
        delete?: never
        options?: never
        head?: never
        patch?: never
        trace?: never
    }
    '/load': {
        parameters: {
            query?: never
            header?: never
            path?: never
            cookie?: never
        }
        get?: never
        put?: never
        post: operations['postLoad']
        delete?: never
        options?: never
        head?: never
        patch?: never
        trace?: never
    }
    '/generate': {
        parameters: {
            query?: never
            header?: never
            path?: never
            cookie?: never
        }
        get?: never
        put?: never
        post: operations['postGenerate']
        delete?: never
        options?: never
        head?: never
        patch?: never
        trace?: never
    }
}
export type webhooks = Record<string, never>
export interface components {
    schemas: never
    responses: never
    parameters: never
    requestBodies: never
    headers: never
    pathItems: never
}
export type $defs = Record<string, never>
export interface operations {
    getHealth: {
        parameters: {
            query?: never
            header?: never
            path?: never
            cookie?: never
        }
        requestBody?: never
        responses: {
            200: {
                headers: {
                    [name: string]: unknown
                }
                content?: never
            }
        }
    }
    postLoad: {
        parameters: {
            query?: never
            header?: never
            path?: never
            cookie?: never
        }
        requestBody: {
            content: {
                'application/json': {
                    modelPath: string
                }
                'multipart/form-data': {
                    modelPath: string
                }
                'text/plain': {
                    modelPath: string
                }
            }
        }
        responses: {
            200: {
                headers: {
                    [name: string]: unknown
                }
                content?: never
            }
        }
    }
    postGenerate: {
        parameters: {
            query?: never
            header?: never
            path?: never
            cookie?: never
        }
        requestBody: {
            content: {
                'application/json': {
                    grammar: string
                    messages: {
                        role: 'model' | 'system' | 'user'
                        content: string
                    }[]
                    n_predict: number
                    /** @default 1 */
                    temperature: number
                    min_p?: number
                    top_p?: number
                    top_k?: number
                }
                'multipart/form-data': {
                    grammar: string
                    messages: {
                        role: 'model' | 'system' | 'user'
                        content: string
                    }[]
                    n_predict: number
                    /** @default 1 */
                    temperature: number
                    min_p?: number
                    top_p?: number
                    top_k?: number
                }
                'text/plain': {
                    grammar: string
                    messages: {
                        role: 'model' | 'system' | 'user'
                        content: string
                    }[]
                    n_predict: number
                    /** @default 1 */
                    temperature: number
                    min_p?: number
                    top_p?: number
                    top_k?: number
                }
            }
        }
        responses: {
            200: {
                headers: {
                    [name: string]: unknown
                }
                content?: never
            }
        }
    }
}
