/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    '/chat/completions': {
        parameters: {
            query?: never
            header?: never
            path?: never
            cookie?: never
        }
        get?: never
        put?: never
        post: operations['postChatCompletions']
        delete?: never
        options?: never
        head?: never
        patch?: never
        trace?: never
    }
}
export type webhooks = Record<string, never>
export interface components {
    schemas: never
    responses: never
    parameters: never
    requestBodies: never
    headers: never
    pathItems: never
}
export type $defs = Record<string, never>
export interface operations {
    postChatCompletions: {
        parameters: {
            query?: never
            header: {
                authorization: string
            }
            path?: never
            cookie?: never
        }
        requestBody: {
            content: {
                'application/json': {
                    grammar: string
                    messages: {
                        role: string
                        content: string
                    }[]
                    n_predict: number
                    /** @default 1 */
                    temperature?: number
                    min_p?: number
                    top_p?: number
                    top_k?: number
                }
                'multipart/form-data': {
                    grammar: string
                    messages: {
                        role: string
                        content: string
                    }[]
                    n_predict: number
                    /** @default 1 */
                    temperature?: number
                    min_p?: number
                    top_p?: number
                    top_k?: number
                }
                'text/plain': {
                    grammar: string
                    messages: {
                        role: string
                        content: string
                    }[]
                    n_predict: number
                    /** @default 1 */
                    temperature?: number
                    min_p?: number
                    top_p?: number
                    top_k?: number
                }
            }
        }
        responses: {
            200: {
                headers: {
                    [name: string]: unknown
                }
                content?: never
            }
        }
    }
}
