/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    '/list': {
        parameters: {
            query?: never
            header?: never
            path?: never
            cookie?: never
        }
        get: operations['getList']
        put?: never
        post?: never
        delete?: never
        options?: never
        head?: never
        patch?: never
        trace?: never
    }
    '/upload': {
        parameters: {
            query?: never
            header?: never
            path?: never
            cookie?: never
        }
        get?: never
        put: operations['putUpload']
        post?: never
        delete?: never
        options?: never
        head?: never
        patch?: never
        trace?: never
    }
    '/download/{collection}/{key}': {
        parameters: {
            query?: never
            header?: never
            path?: never
            cookie?: never
        }
        get: operations['getDownloadByCollectionByKey']
        put?: never
        post?: never
        delete?: never
        options?: never
        head?: never
        patch?: never
        trace?: never
    }
}
export type webhooks = Record<string, never>
export interface components {
    schemas: never
    responses: never
    parameters: never
    requestBodies: never
    headers: never
    pathItems: never
}
export type $defs = Record<string, never>
export interface operations {
    getList: {
        parameters: {
            query?: never
            header?: never
            path?: never
            cookie?: never
        }
        requestBody?: never
        responses: {
            200: {
                headers: {
                    [name: string]: unknown
                }
                content: {
                    'application/json': {
                        key: string
                        collection: string
                        lastUpdate: number
                        deleted?: number
                    }[]
                    'multipart/form-data': {
                        key: string
                        collection: string
                        lastUpdate: number
                        deleted?: number
                    }[]
                    'text/plain': {
                        key: string
                        collection: string
                        lastUpdate: number
                        deleted?: number
                    }[]
                }
            }
        }
    }
    putUpload: {
        parameters: {
            query?: never
            header?: never
            path?: never
            cookie?: never
        }
        requestBody: {
            content: {
                'application/json': {
                    key: string
                    collection: string
                    doc: {
                        id: string
                        lastUpdate: number
                    } & Record<string, never>
                }[]
                'multipart/form-data': {
                    key: string
                    collection: string
                    doc: {
                        id: string
                        lastUpdate: number
                    } & Record<string, never>
                }[]
                'text/plain': {
                    key: string
                    collection: string
                    doc: {
                        id: string
                        lastUpdate: number
                    } & Record<string, never>
                }[]
            }
        }
        responses: {
            200: {
                headers: {
                    [name: string]: unknown
                }
                content?: never
            }
        }
    }
    getDownloadByCollectionByKey: {
        parameters: {
            query?: never
            header?: never
            path: {
                collection: string
                key: string
            }
            cookie?: never
        }
        requestBody?: never
        responses: {
            200: {
                headers: {
                    [name: string]: unknown
                }
                content: {
                    'application/json': {
                        id: string
                        lastUpdate: number
                    }
                    'multipart/form-data': {
                        id: string
                        lastUpdate: number
                    }
                    'text/plain': {
                        id: string
                        lastUpdate: number
                    }
                }
            }
            404: {
                headers: {
                    [name: string]: unknown
                }
                content: {
                    'application/json': string
                    'multipart/form-data': string
                    'text/plain': string
                }
            }
        }
    }
}
