/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/list": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["getList"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/upload/{key}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put: operations["putUploadByKey"];
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/download/{key}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["getDownloadByKey"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: never;
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    getList: {
        parameters: {
            query?: never;
            header: {
                token: string;
            };
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        key: string;
                        lastUpdate: number;
                    }[];
                    "multipart/form-data": {
                        key: string;
                        lastUpdate: number;
                    }[];
                    "text/plain": {
                        key: string;
                        lastUpdate: number;
                    }[];
                };
            };
        };
    };
    putUploadByKey: {
        parameters: {
            query?: never;
            header: {
                token: string;
            };
            path: {
                key: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": {
                    lastUpdate: number;
                    id: string;
                } & {
                    [key: string]: unknown;
                };
                "multipart/form-data": {
                    lastUpdate: number;
                    id: string;
                } & {
                    [key: string]: unknown;
                };
                "text/plain": {
                    lastUpdate: number;
                    id: string;
                } & {
                    [key: string]: unknown;
                };
            };
        };
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    getDownloadByKey: {
        parameters: {
            query?: never;
            header: {
                token: string;
            };
            path: {
                key: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        id: string;
                        lastUpdate: number;
                    };
                    "multipart/form-data": {
                        id: string;
                        lastUpdate: number;
                    };
                    "text/plain": {
                        id: string;
                        lastUpdate: number;
                    };
                };
            };
        };
    };
}
