name: App Build

on:
  workflow_dispatch:
  push:
    branches:
      - ci

env:
  # Necessary for most environments as build failure can occur due to OOM issues
  NODE_OPTIONS: "--max-old-space-size=4096"
  APP_VERSION: "v0.${{ github.run_number }}"
  VITE_CLIENT_VERSION: "v0.${{ github.run_number }}"

jobs:
  create_release:
    name: Create Release
    permissions: write-all
    runs-on: ubuntu-latest
    steps:
      - name: Create Release
        id: create_release
        uses: softprops/action-gh-release@v2
        with:
          name: ${{ env.APP_VERSION }}
          tag_name: ${{ env.APP_VERSION }}
          draft: false
          prerelease: false

  build:
    needs: create_release
    permissions: write-all
    strategy:
      fail-fast: false
      matrix:
        build:
          - name: build-linux
            os: ubuntu-latest
            platform: linux/amd64
          - name: build-mac
            os: macos-latest
            platform: darwin/amd64
          - name: build-windows
            os: windows-latest
            platform: windows/amd64
    runs-on: ${{ matrix.build.os }}
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: '20.14.0'

      - name: Install Node Dependencies
        run: npm ci

      - name: Build Frontend and Backend
        run: npm run build

      - name: Build Electron
        run: npm run make

      - name: Zip installer on Windows
        if: matrix.build.platform == 'windows/amd64'
        run: Compress-Archive -Path out/cybermuse-desktop-win-x64.exe -DestinationPath out/cybermuse-desktop-win-x64.zip

      # Github release files
      - name: Upload Github Release Files
        uses: softprops/action-gh-release@v2
        with:
          tag_name: ${{ env.APP_VERSION }}
          files: |
            out/*.tar.xz
            out/*.zip

      # - name: Setup RClone
      #   uses: AnimMouse/setup-rclone@v1
      #   with:
      #     disable_base64: true
      #     rclone_config: |
      #       [r2]
      #       type = s3
      #       provider = Cloudflare
      #       access_key_id = ${{ secrets.R2_ACCESS_KEY_ID }}
      #       secret_access_key = ${{ secrets.R2_SECRET_ACCESS_KEY }}
      #       endpoint = https://${{ secrets.R2_ACCOUNT_ID }}.r2.cloudflarestorage.com
      #       acl = private
      #       no_check_bucket = true

      # - name: Upload Linux
      #   if: matrix.build.platform == 'linux/amd64'
      #   working-directory: out
      #   run: |
      #     rclone copy cybermuse-desktop-linux-x64.tar.xz r2:chat-app-releases/latest/
      #     rclone copyto cybermuse-desktop-linux-x64.tar.xz r2:chat-app-releases/versions/cybermuse-desktop-${{env.APP_VERSION}}-linux.tar.xz
        
      # - name: Upload Mac
      #   if: matrix.build.platform == 'darwin/amd64'
      #   working-directory: out
      #   run: |
      #     rclone copy cybermuse-desktop-mac-x64.zip r2:chat-app-releases/latest/
      #     rclone copyto cybermuse-desktop-mac-x64.zip r2:chat-app-releases/versions/cybermuse-desktop-${{env.APP_VERSION}}-mac-x64.zip
      #     rclone copy cybermuse-desktop-mac-arm64.zip r2:chat-app-releases/latest/
      #     rclone copyto cybermuse-desktop-mac-arm64.zip r2:chat-app-releases/versions/cybermuse-desktop-${{env.APP_VERSION}}-mac-arm64.zip

      # - name: Archive and Upload Windows
      #   if: matrix.build.platform == 'windows/amd64'
      #   working-directory: out
      #   run: |
      #     Compress-Archive -Path cybermuse-desktop-win-x64.exe -DestinationPath cybermuse-desktop-win-x64.zip
      #     rclone copy cybermuse-desktop-win-x64.zip r2:chat-app-releases/latest/
      #     rclone copyto cybermuse-desktop-win-x64.zip r2:chat-app-releases/versions/cybermuse-desktop-${{env.APP_VERSION}}-win-x64.zip