name: App Build

on:
  workflow_dispatch:
  push:
    tags: ['v*']

jobs:
  build:
    permissions: write-all
    strategy:
      fail-fast: false
      matrix:
        build:
          - name: build-linux
            os: ubuntu-22.04
            platform: linux/amd64
          - name: build-windows
            os: ubuntu-22.04
            platform: windows/amd64
          - name: build-mac
            os: macos-latest
            platform: darwin/amd64
    runs-on: ${{ matrix.build.os }}
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      # Covers both libgtk for Linux build and nsis for Windows installer build
      # - name: Install System Dependencies
      #   if: runner.os == 'Linux'
      #   run: sudo apt-get update && sudo apt-get install -y zip nsis libgtk-3-0 libwebkit2gtk-4.0-dev gcc-aarch64-linux-gnu

      - name: Setup Bun
        uses: oven-sh/setup-bun@v2
        with:
          bun-version: latest

      - name: Build App
        run: |
          bun install
          bun run make

      - name: Compress Linux Binary
        if: matrix.build.platform == 'linux/amd64'
        run: cd build/bin && tar -cJf cybermuse-linux-x64.tar.xz cybermuse

      - name: Compress Windows Binary/Installer
        if: matrix.build.platform == 'windows/amd64'
        run: |
          cd build/bin
          zip -r cybermuse-windows-x64.zip cybermuse.exe
          zip -r cybermuse-windows-installer.zip cybermuse-amd64-installer.exe

      - name: Compress Mac Binary
        if: matrix.build.platform == 'darwin/amd64'
        run: cd build/bin && zip -r cybermuse-mac-x64.zip cybermuse.app

      - name: Upload Github Release Files
        uses: softprops/action-gh-release@v2
        with:
          tag_name: ${{ github.ref_name }}
          files: |
            build/bin/*.tar.xz
            build/bin/*.zip

      # - name: Setup RClone
      #   uses: AnimMouse/setup-rclone@v1
      #   with:
      #     disable_base64: true
      #     rclone_config: |
      #       [r2]
      #       type = s3
      #       provider = Cloudflare
      #       access_key_id = ${{ secrets.R2_ACCESS_KEY_ID }}
      #       secret_access_key = ${{ secrets.R2_SECRET_ACCESS_KEY }}
      #       endpoint = https://${{ secrets.R2_ACCOUNT_ID }}.r2.cloudflarestorage.com
      #       acl = private
      #       no_check_bucket = true

      # - name: Upload Linux
      #   if: matrix.build.platform == 'linux/amd64'
      #   working-directory: out
      #   run: |
      #     rclone copy cybermuse-desktop-linux-x64.tar.xz r2:chat-app-releases/latest/
      #     rclone copyto cybermuse-desktop-linux-x64.tar.xz r2:chat-app-releases/versions/cybermuse-desktop-${{env.APP_VERSION}}-linux.tar.xz
        
      # - name: Upload Mac
      #   if: matrix.build.platform == 'darwin/amd64'
      #   working-directory: out
      #   run: |
      #     rclone copy cybermuse-desktop-mac-x64.zip r2:chat-app-releases/latest/
      #     rclone copyto cybermuse-desktop-mac-x64.zip r2:chat-app-releases/versions/cybermuse-desktop-${{env.APP_VERSION}}-mac-x64.zip
      #     rclone copy cybermuse-desktop-mac-arm64.zip r2:chat-app-releases/latest/
      #     rclone copyto cybermuse-desktop-mac-arm64.zip r2:chat-app-releases/versions/cybermuse-desktop-${{env.APP_VERSION}}-mac-arm64.zip

      # - name: Archive and Upload Windows
      #   if: matrix.build.platform == 'windows/amd64'
      #   working-directory: out
      #   run: |
      #     Compress-Archive -Path cybermuse-desktop-win-x64.exe -DestinationPath cybermuse-desktop-win-x64.zip
      #     rclone copy cybermuse-desktop-win-x64.zip r2:chat-app-releases/latest/
      #     rclone copyto cybermuse-desktop-win-x64.zip r2:chat-app-releases/versions/cybermuse-desktop-${{env.APP_VERSION}}-win-x64.zip