name: App Build

on:
  workflow_dispatch:
  push:
    branches:
      - ci

env:
  # Necessary for most environments as build failure can occur due to OOM issues
  NODE_OPTIONS: "--max-old-space-size=4096"
  LLAMA_CPP_VERSION: "b3066"
  APP_VERSION: "v0.${{ github.run_number }}"
  VITE_CLIENT_VERSION: "v0.${{ github.run_number }}"

jobs:
  build:
    strategy:
      fail-fast: false
      matrix:
        build:
          - name: build-linux
            os: ubuntu-latest
            target-platform: linux/amd64
          - name: build-mac
            os: macos-latest
            target-platform: darwin/amd64
          - name: build-windows
            os: ubuntu-latest
            target-platform: windows/amd64

    runs-on: ${{ matrix.build.os }}
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Install System Dependencies
        if: runner.os == 'Linux'
        run: sudo apt-get update && sudo apt-get install -y zip nsis

      - name: Linux specific dependencies
        if: matrix.build.target-platform == 'linux/amd64'
        run: sudo apt-get update && sudo apt-get install -y libgtk-3-0 libwebkit2gtk-4.0-dev gcc-aarch64-linux-gnu

      - name: Setup Go
        uses: actions/setup-go@v5
        with:
          go-version: '1.22.2'

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: '20'

      - name: Setup RClone
        uses: AnimMouse/setup-rclone@v1
        with:
          disable_base64: true
          rclone_config: |
            [r2]
            type = s3
            provider = Cloudflare
            access_key_id = ${{ secrets.R2_ACCESS_KEY_ID }}
            secret_access_key = ${{ secrets.R2_SECRET_ACCESS_KEY }}
            endpoint = https://${{ secrets.R2_ACCOUNT_ID }}.r2.cloudflarestorage.com
            acl = private
            no_check_bucket = true

      - name: Install Wails
        run: go install github.com/wailsapp/wails/v2/cmd/wails@latest

      # Get llama.cpp binaries specific to the platform
      - name: Get llama.cpp server binary
        if: matrix.build.target-platform == 'linux/amd64'
        run: curl --silent -L https://github.com/ggerganov/llama.cpp/releases/download/${{env.LLAMA_CPP_VERSION}}/llama-${{env.LLAMA_CPP_VERSION}}-bin-ubuntu-x64.zip > llamacpp.zip

      - name: Get llama.cpp server binary
        if: matrix.build.target-platform == 'darwin/amd64'
        run: curl --silent -L https://github.com/ggerganov/llama.cpp/releases/download/${{env.LLAMA_CPP_VERSION}}/llama-${{env.LLAMA_CPP_VERSION}}-bin-macos-x64.zip > llamacpp.zip

      - name: Get llama.cpp server binary
        if: matrix.build.target-platform == 'windows/amd64'
        run: curl --silent -L https://github.com/ggerganov/llama.cpp/releases/download/${{env.LLAMA_CPP_VERSION}}/llama-${{env.LLAMA_CPP_VERSION}}-bin-win-vulkan-x64.zip > llamacpp.zip

      - name: Extract
        run: unzip -j llamacpp.zip -d build/llamacpp/

      - name: Build Wails
        run: wails build -skipbindings -platform=${{ matrix.build.target-platform }} -nsis=${{ matrix.build.target-platform == 'windows/amd64' }} -ldflags "-X main.version=${{env.APP_VERSION}}"
        shell: bash

      - name: Archive and Upload Linux
        if: matrix.build.target-platform == 'linux/amd64'
        run: |
          cd build/bin
          tar -acf chat-linux.tar.gz *
          rclone copy chat-linux.tar.gz r2:chat-app-releases/latest/
          rclone copy chat-linux.tar.gz r2:chat-app-releases/versions/chat-${{env.APP_VERSION}}-linux.tar.gz
        
      - name: Archive and Upload Mac
        if: matrix.build.target-platform == 'darwin/amd64'
        run: |
          cd build/bin
          ditto -c -k --keepParent chat.app chat-mac-x86.zip
          rclone copy chat-mac-x86.zip r2:chat-app-releases/latest/
          rclone copy chat-mac-x86.zip r2:chat-app-releases/versions/chat-${{env.APP_VERSION}}-mac-x86.zip

      - name: Archive and Upload Windows
        if: matrix.build.target-platform == 'windows/amd64'
        run: |
          cd build/bin
          zip chat-windows.zip chat-amd64-installer.exe
          rclone copy chat-windows.zip r2:chat-app-releases/latest/
          rclone copy chat-windows.zip r2:chat-app-releases/versions/chat-${{env.APP_VERSION}}-windows.zip
